[package]
name = "bamboo-groves-frontend-base"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bamboo-groves-frontend-base-routing = { path = "routing" }
