[package]
name = "bamboo-frontend-section-final-fantasy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { path = "../../base/api" }
bamboo-frontend-base-error = { path = "../../base/error" }
bamboo-entities = { path = "../../../entities" }

gloo-dialogs = { workspace = true }
log = { workspace = true }
strum = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew_icons = { workspace = true }
yew-hooks = { workspace = true }