[package]
name = "bamboo-frontend-section-licenses"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { path = "../../base/api" }
bamboo-entities = { path = "../../../entities" }

chrono = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }