[package]
name = "bamboo-frontend-section-licenses"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-entities = { workspace = true }
bamboo-frontend-base-api = { workspace = true }

chrono = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }