[package]
name = "bamboo-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-pandas = { path = "pandas", optional = true }

[features]
default = []
pandas = ["dep:bamboo-frontend-pandas"]
