[package]
name = "sheef-frontend"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sheef-entities = { path = "../entities", default-features = false }

yew = { version = "0.20.0", features = ["csr", "hydration"] }
yew-router = "0.17.0"
wasm-logger = "0.2.0"
web-sys = "0.3.64"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
async-trait = "0.1.71"
gloo = { version = "0.8.1", default-features = false, features = ["storage", "net"] }
bounce = { version = "0.7.0", features = ["query", "helmet"] }
getrandom = { version = "0.2.10", features = ["js"] }
num-traits = "0.2.15"
rand = "0.8.5"
yew-hooks = "0.2.0"
yew-feather = { version = "1.0.0" }
futures = "0.3.28"

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }