[package]
name = "bamboo-pandas-frontend-base-error"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-pandas-frontend-base-api = { path = "../api" }
bamboo-common = { path = "../../../../common", features = ["frontend"] }

gloo-utils = { workspace = true }
yew = { workspace = true }