[package]
name = "bamboo-frontend-base-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-entities = { workspace = true }
bounce = { workspace = true }
gloo-storage = { workspace = true }