.base-cache:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - target/
      - /usr/local/cargo/registry

.base-trunk:
  extends:
    - .base-cache
  image:
    name: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
    pull_policy: always

.base-kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKERHUB_AND_HARBOR > /kaniko/.docker/config.json

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  extends:
    - .base-trunk
  script:
    - cargo clippy -p pandaparty
    - cargo clippy -p pandaparty-frontend
    - cargo check -p pandaparty
    - cargo check -p pandaparty-frontend

test-build-backend:
  stage: build
  extends:
    - .base-trunk
  script:
    - cargo build --release

test-build-frontend:
  stage: build
  extends:
    - .base-trunk
  script:
    - trunk build --release

docker-build:
  stage: deploy
  extends:
    - .base-kaniko
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:${CI_COMMIT_TAG}"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

docker-build-testing:
  stage: deploy
  extends:
    - .base-kaniko
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:1.5.3-test-$CI_PIPELINE_IID"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile