stages:
  - lint
  - build
  - deploy

lint:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: lint
  script:
    - cargo clippy -p pandaparty
    - cargo clippy -p pandaparty-frontend
    - cargo check -p pandaparty
    - cargo check -p pandaparty-frontend

test-build-backend:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - cargo build --release

test-build-frontend:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - trunk build --release

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_HARBOR_ONLY > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:${CI_COMMIT_TAG}"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

docker-build-testing:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_HARBOR_ONLY > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/creastina/pandaparty:testing"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
