docker-build:
  image: quay.imanuel.dev/dockerhub/library---docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.imanuel.dev
  script:
    - docker build --pull -t "quay.imanuel.dev/creastina/sheef:3.${CI_PIPELINE_IID}" -f ./Dockerfile .
    - docker tag "quay.imanuel.dev/creastina/sheef:3.${CI_PIPELINE_IID}" "quay.imanuel.dev/creastina/sheef:latest"
    - docker push "quay.imanuel.dev/creastina/sheef:3.${CI_PIPELINE_IID}"
    - docker push "quay.imanuel.dev/creastina/sheef:latest"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-docs-build:
  image: quay.imanuel.dev/dockerhub/library---docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.imanuel.dev
  script:
    - docker build --pull -t "quay.imanuel.dev/creastina/sheef-api-docs:3.${CI_PIPELINE_IID}" -f ./api-docs/Dockerfile ./api-docs
    - docker tag "quay.imanuel.dev/creastina/sheef-api-docs:3.${CI_PIPELINE_IID}" "quay.imanuel.dev/creastina/sheef-api-docs:latest"
    - docker push "quay.imanuel.dev/creastina/sheef-api-docs:3.${CI_PIPELINE_IID}"
    - docker push "quay.imanuel.dev/creastina/sheef-api-docs:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile

build-merge-request:
  image: quay.imanuel.dev/dockerhub/library---rust:1.70-alpine3.18
  stage: build
  script:
    - apk add musl-dev
    - rustup target add wasm32-unknown-unknown
    - cargo install --locked trunk
    - trunk build --release
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"