stages:
  - lint
  - build
  - deploy

lint:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: lint
  script:
    - cargo check

test-build:
  image: quay.imanuel.dev/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - cargo build --release
    - trunk build --release

docker-build:
  image: quay.imanuel.dev/dockerhub/library---docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.imanuel.dev
  script:
    - docker build --pull -t "quay.imanuel.dev/creastina/pandaparty:${CI_COMMIT_TAG}" -f ./Dockerfile .
    - docker tag "quay.imanuel.dev/creastina/pandaparty:${CI_COMMIT_TAG}" "quay.imanuel.dev/creastina/pandaparty:latest"
    - docker push "quay.imanuel.dev/creastina/pandaparty:${CI_COMMIT_TAG}"
    - docker push "quay.imanuel.dev/creastina/pandaparty:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

docker-build-testing:
  image: quay.imanuel.dev/dockerhub/library---docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.imanuel.dev
  script:
    - docker build --pull -t "quay.imanuel.dev/creastina/pandaparty:testing" -f ./Dockerfile .
    - docker push "quay.imanuel.dev/creastina/pandaparty:testing"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
