stages:
  - lint
  - build
  - deploy

lint:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: lint
  script:
    - cargo clippy -p pandaparty
    - cargo clippy -p pandaparty-frontend
    - cargo check

test-build:
  image: harbor.ulbricht.casa/imanuel/trunk-docker-base-image:latest
  stage: build
  script:
    - cargo build --release
    - trunk build --release

docker-build:
  image: harbor.ulbricht.casa/dockerhub/library/docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" harbor.ulbricht.casa
  script:
    - docker build --pull -t "harbor.ulbricht.casa/creastina/pandaparty:${CI_COMMIT_TAG}" -f ./Dockerfile .
    - docker tag "harbor.ulbricht.casa/creastina/pandaparty:${CI_COMMIT_TAG}" "harbor.ulbricht.casa/creastina/pandaparty:latest"
    - docker push "harbor.ulbricht.casa/creastina/pandaparty:${CI_COMMIT_TAG}"
    - docker push "harbor.ulbricht.casa/creastina/pandaparty:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

docker-build-testing:
  image: harbor.ulbricht.casa/dockerhub/library---docker:stable
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" harbor.ulbricht.casa
  script:
    - docker build --pull -t "harbor.ulbricht.casa/creastina/pandaparty:testing" -f ./Dockerfile .
    - docker push "harbor.ulbricht.casa/creastina/pandaparty:testing"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
