[package]
name = "sheef_planing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stderrlog = "0.5.4"
log = "0.4.19"
actix-web = "4.3.1"
sheef_backend = { path = "backend" }

[workspace]
members = [
    "backend",
    "database",
    "entities",
    "rusty",
    "utils"
]

[profile.release]
# less code to include into binary
panic = "abort"
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = "z"
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true