[package]
name = "sheef_planing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stderrlog = "0.5.4"
log = "0.4.19"
actix-web = "4.3.1"
sheef_backend = { path = "backend" }