[package]
name = "bamboo"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bamboo-backend = { path = "backend" }
bamboo-dbal = { path = "dbal" }
bamboo-entities = { path = "entities" }
bamboo-migration = { path = "migration" }
bamboo-services = { path = "services" }

actix-web = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
sea-orm = { workspace = true }
sentry = { workspace = true }
sentry-actix = { workspace = true }
sentry-log = { workspace = true }
env_logger = { workspace = true }

[workspace]
members = [
    "backend",
    "dbal",
    "entities",
    "error",
    "macros",
    "migration",
    "services",
    "sse",
]

[workspace.package]
version = "1.5.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
actix-web = "4.4.0"
actix-web-lab = "0.20.1"
base64 = "0.21.5"
bcrypt = "0.15.0"
bounce = { version = "0.9.0", features = ["query", "helmet"] }
bytestring = "1.3.1"
chacha20poly1305 = "0.10.1"
chrono = { version = "0.4.31", features = ["serde"] }
color-art = "0.3.7"
date-range = "0.3.0"
either = "1.9.0"
env_logger = "0.10.1"
futures = "0.3.28"
futures-util = "0.3.28"
lettre = { version = "0.11.0", features = ["tokio1-rustls-tls", "smtp-transport", "pool", "hostname", "builder"], default-features = false }
log = "0.4.20"
parking_lot = "0.12.1"
pbkdf2 = "0.12.2"
quote = "1.0.33"
rand = "0.8.5"
sea-orm = { version = "0.12.9", features = ["with-json", "runtime-actix-rustls", "sqlx-postgres"] }
sea-orm-migration = { version = "0.12.6", features = ["sqlx-mysql", "runtime-tokio-rustls"] }
sentry = { version = "0.32.0", default-features = false, features = ["backtrace", "contexts", "panic", "transport", "debug-images", "reqwest", "rustls"] }
sentry-actix = "0.32.0"
sentry-log = "0.32.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.8"
strum = "0.25.0"
strum_macros = "0.25.2"
syn = "2.0.39"
tokio = "1.34.0"
totp-rs = { version = "5.4.0", features = ["qr", "gen_secret"] }
uuid = { version = "1.4.1", features = ["v4"] }
