[package]
name = "pandaparty"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pandaparty-backend = { path = "backend" }
pandaparty-migration = { path = "migration" }
pandaparty-entities = { path = "entities" }
pandaparty-dbal = { path = "dbal" }

stderrlog = "0.5.4"

actix-web = { workspace = true }
actix-web-lab = { workspace = true, features = ["spa"] }
log = { workspace = true }
rand = { workspace = true }
sea-orm = { workspace = true }

[workspace]
members = [
    "backend",
    "dbal",
    "entities",
    "frontend",
    "migration",
]

[workspace.package]
version = "4.0.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.3.1"
actix-web-lab = "0.19.1"
bcrypt = "0.15.0"
chrono = { version = "0.4.26", features = ["serde"] }
color-art = "0.3.2"
date-range = "0.3.0"
log = "0.4.19"
sea-orm = { version = "0.12.2", features = ["with-json", "runtime-actix-rustls", "sqlx-postgres"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
rand = "0.8.5"

[profile.release]
# less code to include into binary
panic = "abort"
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = "z"
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
strip = "symbols"