[package]
name = "pandaparty"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pandaparty-backend = { path = "backend" }
pandaparty-migration = { path = "migration" }
pandaparty-entities = { path = "entities" }
pandaparty-dbal = { path = "dbal" }

stderrlog = "0.5.4"
tokio = { version = "1.29.1", features = ["full"] }
anyhow = "1.0.71"

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
actix-web-lab = { workspace = true, features = ["spa"] }
actix-web = { workspace = true }
sea-orm = { workspace = true }

[workspace]
members = [
    "backend",
    "dbal",
    "entities",
    "frontend",
    "migration",
    "utils"
]

[workspace.dependencies]
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
chrono = { version = "0.4.26", features = ["serde"] }
actix-web-lab = "0.19.1"
actix-web = "4.3.1"
sea-orm = { version = "0.11.3", features = ["with-json", "runtime-actix-rustls", "sqlx-postgres"] }
bcrypt = "0.15.0"

[profile.release]
# less code to include into binary
panic = "abort"
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = "z"
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
strip = "symbols"