[package]
name = "sheef_planing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sheef_backend = { path = "backend" }

stderrlog = "0.5.4"
actix-web = "4.3.1"

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

[workspace]
members = [
    "backend",
    "database",
    "entities",
    "rusty",
    "utils"
]

[workspace.dependencies]
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
chrono = { version = "0.4.26", features = ["serde"] }

[profile.release]
# less code to include into binary
panic = "abort"
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = "z"
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
strip = "symbols"