[package]
name = "pandaparty"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pandaparty-backend = { path = "backend" }
pandaparty-dbal = { path = "dbal" }
pandaparty-entities = { path = "entities" }
pandaparty-migration = { path = "migration" }
pandaparty-services = { path = "services" }

actix-web = { workspace = true }
actix-web-lab = { workspace = true, features = ["spa"] }
log = { workspace = true }
rand = { workspace = true }
sea-orm = { workspace = true }
stderrlog = { workspace = true }

[workspace]
members = [
    "backend",
    "dbal",
    "entities",
    "frontend",
    "migration",
    "services",
]

[workspace.package]
version = "1.1.1"
edition = "2021"

[workspace.dependencies]
actix-web = "4.4.0"
actix-web-lab = "0.19.1"
async-trait = "0.1.73"
bcrypt = "0.15.0"
bounce = { version = "0.8.0", features = ["query", "helmet"] }
chrono = { version = "0.4.31", features = ["serde"] }
color-art = "0.3.7"
date-range = "0.3.0"
either = "1.9.0"
futures = "0.3.28"
futures-util = "0.3.28"
gloo = { version = "0.10.0", default-features = false, features = ["storage", "net"] }
lettre = { version = "0.10.4", features = ["tokio1-rustls-tls", "smtp-transport", "pool", "hostname", "builder"], default-features = false }
log = "0.4.20"
parking_lot = "0.12.1"
rand = "0.8.5"
sea-orm = { version = "0.12.3", features = ["with-json", "runtime-actix-rustls", "sqlx-postgres"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.7"
stderrlog = "0.5.4"
strum = "0.25.0"
strum_macros = "0.25.2"
stylist = { version = "0.12.1", features = ["yew"] }
totp-rs = { version = "5.3.0", features = ["qr", "gen_secret"] }
uuid = { version = "1.4.1", features = ["v4"] }
wasm-bindgen = "0.2.87"
wasm-logger = "0.2.0"
web-sys = "0.3.64"
yew = { version = "0.20.0", features = ["csr", "hydration"] }
yew-cosmo = "0.15.20"
yew_icons = { version = "0.7.3", features = ["lucide"] }
yew-hooks = "0.2.0"
yew-router = "0.17.0"

[profile.release]
# less code to include into binary
panic = "abort"
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = "z"
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
strip = "symbols"