version: "3"
services:
  pandaparty-postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: pandaparty
      POSTGRES_PASSWORD: pandaparty
      POSTGRES_ROOT_PASSWORD: pandaparty
      POSTGRES_USER: pandaparty
    ports:
      - "5434:5432"