version: "3"
services:
  pandaparty-postgres:
    image: library/postgres:15-alpine
    environment:
      POSTGRES_DB: pandaparty
      POSTGRES_PASSWORD: pandaparty
      POSTGRES_ROOT_PASSWORD: pandaparty
      POSTGRES_USER: pandaparty
    ports:
      - "5434:5432"
  pandaparty-mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    ports:
      - "1325:1025"
      - "8325:8025"