version: "3"
services:
  pandaparty-postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: sheef
      POSTGRES_PASSWORD: sheef
      POSTGRES_ROOT_PASSWORD: sheef
      POSTGRES_USER: sheef
    ports:
      - "6543:5432"