version: "3"
services:
  pandaparty-postgres:
    image: harbor.ulbricht.casa/proxy/library/postgres:15-alpine
    environment:
      POSTGRES_DB: pandaparty
      POSTGRES_PASSWORD: pandaparty
      POSTGRES_ROOT_PASSWORD: pandaparty
      POSTGRES_USER: pandaparty
    ports:
      - "5434:5432"