version: "3"
services:
  bamboo-postgres:
    image: library/postgres:15-alpine
    environment:
      POSTGRES_DB: bamboo
      POSTGRES_PASSWORD: bamboo
      POSTGRES_ROOT_PASSWORD: bamboo
      POSTGRES_USER: bamboo
    ports:
      - "5434:5432"
  bamboo-mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    ports:
      - "1325:1025"
      - "8325:8025"