version: "3"
services:
  bamboo-postgres:
    image: library/postgres:14-alpine
    environment:
      POSTGRES_DB: bamboo
      POSTGRES_PASSWORD: bamboo
      POSTGRES_ROOT_PASSWORD: bamboo
      POSTGRES_USER: bamboo
    ports:
      - "5434:5432"
  bamboo-mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    ports:
      - "1325:1025"
      - "8325:8025"
  bamboo-nats:
    image: library/nats:2
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - -js
  bamboo-proxy:
    image: library/traefik:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8070:80"
      - "8060:8060"
    volumes:
      - "./traefik/traefik_dynamic.yml:/dynamic.yml:ro"
    command:
      - --entryPoints.web.address=:80
      - --entryPoints.traefik.address=:8060
      - --providers.file.filename=/dynamic.yml
      - --api.insecure=true
      - --api.dashboard=true