[build]
# The index HTML file to drive the bundling process.
target = "groves/frontend/index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist-groves"
# The public URL from which assets are to be served.
public_url = "/static/"
wasm-opt = "z"

[watch]
watch = ["common/core", "common/frontend", "groves/frontend"]