[package]
name = "bamboo-groves-frontend-sections"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bamboo-groves-frontend-section-layout = { path = "layout" }
bamboo-groves-frontend-section-login = { path = "login" }
bamboo-groves-frontend-section-users = { path = "users" }
