[package]
name = "pandaparty-backend"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pandaparty-dbal = { path = "../dbal" }
pandaparty-entities = { path = "../entities" }
pandaparty-services = { path = "../services" }

actix-web = { workspace = true }
actix-web-lab = { workspace = true }
chrono = { workspace = true }
date-range = { workspace = true }
futures-util = { workspace = true }
lettre = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }