[package]
name = "bamboo-frontend-pandas-base-error"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }

gloo-utils = { workspace = true }
yew = { workspace = true }