[package]
name = "bamboo-frontend-section-mod-area"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { path = "../../base/api" }
bamboo-frontend-base-error = { path = "../../base/error" }
bamboo-frontend-base-routing = { path = "../../base/routing" }
bamboo-frontend-base-storage = { path = "../../base/storage" }
bamboo-entities = { path = "../../../entities" }

bounce = { workspace = true }
log = { workspace = true }
yew = { workspace = true }
yew-cosmo = { workspace = true }
yew-autoprops = { workspace = true }
yew-hooks = { workspace = true }
yew-router = { workspace = true }