[package]
name = "bamboo-frontend-base-error"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { path = "../api" }

bamboo-entities = { workspace = true }
gloo-utils = { workspace = true }
yew = { workspace = true }