[package]
name = "bamboo-frontend-section-layout"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { workspace = true }
bamboo-frontend-base-error = { workspace = true }
bamboo-frontend-base-routing = { workspace = true }
bamboo-frontend-base-storage = { workspace = true }
bamboo-frontend-section-authentication = { workspace = true }
bamboo-frontend-section-bamboo = { workspace = true }
bamboo-frontend-section-final-fantasy = { workspace = true }
bamboo-frontend-section-legal = { workspace = true }
bamboo-frontend-section-licenses = { workspace = true }
bamboo-frontend-section-support = { workspace = true }

bamboo-entities = { workspace = true }
bounce = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }
yew-router = { workspace = true }