[package]
name = "bamboo-services"
version.workspace = true
edition.workspace = true
license-file.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
