version: 2
updates:
  - package-ecosystem: cargo
    directory: /common
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /pandas
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /groves
    schedule:
      interval: daily