[package]
name = "bamboo-pandas-frontend-base"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../common" }
bamboo-pandas-frontend-base-error = { path = "error" }
bamboo-pandas-frontend-base-routing = { path = "routing" }
bamboo-pandas-frontend-base-storage = { path = "storage" }
