[package]
name = "bamboo-pandas-frontend-section-layout"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }
bamboo-pandas-frontend-base = { path = "../../base" }
bamboo-pandas-frontend-section-authentication = { path = "../../sections/authentication" }
bamboo-pandas-frontend-section-bamboo = { path = "../../sections/bamboo" }
bamboo-pandas-frontend-section-final-fantasy = { path = "../../sections/final-fantasy" }
bamboo-pandas-frontend-section-legal = { path = "../../sections/legal" }
bamboo-pandas-frontend-section-licenses = { path = "../../sections/licenses" }
bamboo-pandas-frontend-section-mod-area = { path = "../../sections/mod-area" }
bamboo-pandas-frontend-section-support = { path = "../../sections/support" }

bounce = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
web-sys = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }
yew-router = { workspace = true }