[package]
name = "bamboo-pandas-frontend-section-final-fantasy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }
bamboo-pandas-frontend-base = { path = "../../base" }

gloo-dialogs = { workspace = true }
log = { workspace = true }
strum = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew_icons = { workspace = true }
yew-hooks = { workspace = true }