[package]
name = "bamboo-frontend-pandas-section-licenses"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }
bamboo-frontend-pandas-base = { path = "../../base" }

chrono = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }