[package]
name = "bamboo-common-backend-logging"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log = { workspace = true }
env_logger = { workspace = true}
