[package]
name = "bamboo-groves-frontend-section-users"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }

bounce = { workspace = true }
gloo-utils = { workspace = true }
log = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }
yew_icons = { workspace = true }
yew-router = { workspace = true }
