[package]
name = "bamboo-pandas-frontend-base-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-pandas-frontend-base-storage = { path = "../storage" }
bamboo-common = { path = "../../../../common", features = ["frontend"] }

gloo-net = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }