[package]
name = "bamboo-frontend-section-support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-frontend-base-api = { workspace = true }

bamboo-entities = { workspace = true }
bounce = { workspace = true }
log = { workspace = true }
stylist = { workspace = true }
yew = { workspace = true }
yew-cosmo = { workspace = true }