[package]
name = "bamboo-groves-frontend-section-layout"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common = { path = "../../../../common", features = ["frontend"] }
bamboo-groves-frontend-base = { path = "../../base" }
bamboo-groves-frontend-section-login = { path = "../../sections/login" }

bounce = { workspace = true }
gloo-utils = { workspace = true }
jsonwebtokens = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
stylist = { workspace = true }
url = { workspace = true }
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-cosmo = { workspace = true }
yew-hooks = { workspace = true }
yew-oauth2 = { workspace = true }
yew-router = { workspace = true }