[package]
name = "bamboo-common-backend-notification"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bamboo-common-backend-mq = { path = "../message_queue" }
bamboo-common-core = { path = "../../core" }

async-nats = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["async-nats", "bytes", "ciborium"]